dependencies:
  - name: metallb
    version: 0.8.3
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: nginx-ingress
    version: 1.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
