address: "192.168.179.6-192.168.179.10"

metallb:
  existingConfigMap: metallb-config

nginx-ingress:
  controller:
    nodeSelector: 
      beta.kubernetes.io/arch: "amd64"
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/arch: "amd64"
